Kushol Huq | DOM Creation
kusholhuq/lfz-alumni-code-solutions pull request #58
Opened 2021-11-11 04:56 UTC by kusholhuq

![image](https://user-images.githubusercontent.com/54958460/141239805-b612adc5-4235-4e53-9080-9ca3b654bafc.png)

2022-01-09 14:34 UTC, thebearingedge requested changes

2022-01-09 14:34 UTC, thebearingedge commented on exercises/dom-creation/main.js
> +  row.appendChild(pokemon);
If you pass the entire object within `pokedex[i]` you won't have to force your function to dig around in the array to find it.

2022-01-09 14:34 UTC, thebearingedge commented on exercises/dom-creation/main.js
> +  }
This is unnecessary if `pokemon` is already the object the function wants.

2022-01-10 02:07 UTC, kusholhuq commented on exercises/dom-creation/main.js
> +  }
Ohhh right, yeah added an extra step for no reason, which caused it to begin a new for loop every iteration of the outer loop.

2022-01-10 02:09 UTC, thebearingedge approved these changes

2022-01-11 00:47 UTC, merged